export enum TenantType {
  SYSTEM = 'SYSTEM',
  SOCIETY = 'SOCIETY',
  SHOP = 'SHOP',
}

export enum UserRole {
  // Owner Level
  SYSTEM_OWNER = 'SYSTEM_OWNER',
  SYSTEM_EMPLOYEE = 'SYSTEM_EMPLOYEE',

  // Society Level
  SOCIETY_ADMIN = 'SOCIETY_ADMIN',
  SOCIETY_COMMITTEE = 'SOCIETY_COMMITTEE',
  RESIDENT_OWNER = 'RESIDENT_OWNER',
  RESIDENT_TENANT = 'RESIDENT_TENANT',
  SOCIETY_EMPLOYEE = 'SOCIETY_EMPLOYEE',
  FAMILY_MEMBER = 'FAMILY_MEMBER',

  // Shop Level
  SHOP_ADMIN = 'SHOP_ADMIN',
  SHOP_OWNER = 'SHOP_OWNER',
  SHOP_CLIENT = 'SHOP_CLIENT',
}

export const OWNER_LEVEL_ROLES = [UserRole.SYSTEM_OWNER, UserRole.SYSTEM_EMPLOYEE];
export const SOCIETY_LEVEL_ROLES = [
  UserRole.SOCIETY_ADMIN,
  UserRole.SOCIETY_COMMITTEE,
  UserRole.RESIDENT_OWNER,
  UserRole.RESIDENT_TENANT,
  UserRole.SOCIETY_EMPLOYEE,
  UserRole.FAMILY_MEMBER,
];
export const SHOP_LEVEL_ROLES = [UserRole.SHOP_ADMIN, UserRole.SHOP_OWNER, UserRole.SHOP_CLIENT];
